# Configuration file for use of a custom toolchain
#
# (c) Koheron

# Target host
cross-compile: arm-linux-gnueabihf

devices:
    # Core devices
    - ../devices/dev_mem.yaml
    - ../middleware/drivers/core/xadc.hpp
    - ../middleware/drivers/core/gpio.hpp
    - ../middleware/drivers/core/oscillo.hpp
    - ../middleware/drivers/core/dac.hpp
    
    # Misc
    - ../middleware/tests/tests.hpp
    - ../middleware/misc/init_tasks.hpp

