# Config for running tests on localhost
#
# To be compiled on the local computer
#
# (c) Koheron

# Local config does not contain dev_mem

# Executable name
server-name: kserverd

cross-compile: ""

arch_flags:
  - march=native

defines:
  - DEBUG_KSERVER
  # - RELEASE_KSERVER
  - LOCAL

debug:
  status: yes # set to yes to compile in debug mode
  flags:
    # - rdynamic
    - g

optimization_flags:
  - O3

devices:
    - tests/tests.hpp
    - tests/benchmarks.hpp
    #- tests/eigen_tests.hpp
    - tests/exception_tests.hpp
    - tests/uses_context.hpp
